#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloWorld.Resource", IsApplication=true)]

namespace HelloWorld
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int body = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int head = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int Icon = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int leftarm = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int leftleg = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int letter_bg = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int letter_down = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int letter_up = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int poster = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int rightarm = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int rightleg = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int stair = 2130771979;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020005
			public const int backBtn = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int body = 2130837510;
			
			// aapt resource value: 0x7F020000
			public const int ButtonSubmit = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Button_Exit = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Button_HighScores = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Button_NewGame = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int CurrentAnswerLayout = 2130837508;
			
			// aapt resource value: 0x7F020007
			public const int gridView = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int head = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int highscore1 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int highscore2 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int highscore3 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int highscore4 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int highscore5 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int left_arm = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int left_leg = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int myButton = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int player = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int poster = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int profilebutton1 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int profilebutton2 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int profilebutton3 = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int profilebutton4 = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int profilebutton5 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int question = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int right_arm = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int right_leg = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int score = 2130837531;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int GameLayout = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Highscores = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int MainMenu = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int hello = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
